### ISSUE TITLE
Material issues when export mmd model to usdz format

### ISSUE THREAD

**Issue by Lcyre1** [MMD-Blender/blender_mmd_tools#256]
issue1:
Some spa / sph texture are not converted when click Convert to blender button

issue2:

some material lost when export to usdz format ( even after click Seprate by Materials)

step:
1: import a pmx model
2: click Convert to blender button
3: click File -> Export -> .usd* and change file name extension to usdz

original model

<img width="1217" height="744" alt="Image" src="https://github.com/user-attachments/assets/104a5c61-38a7-4880-ae4d-f7d606c1d3ea" />

model after step 2

<img width="1229" height="753" alt="Image" src="https://github.com/user-attachments/assets/ddb8147a-daf3-48fd-8ce2-7c9cf73d4691" />

exported model

<img width="1174" height="694" alt="Image" src="https://github.com/user-attachments/assets/94346911-3d48-47cf-8c40-0ab201f37fca" />

**Comment by rintrint** [comment]
Cannot reproduce.

issue1 test:
<img width="1281" height="801" alt="Image" src="https://github.com/user-attachments/assets/69d77d60-c942-4631-8bcf-0d47c8b4e54f" />

issue2 test:
<img width="1281" height="801" alt="Image" src="https://github.com/user-attachments/assets/531ca943-43b5-4abe-b6aa-e41cccea73c4" />

**Comment by Lcyre1** [comment]
[Archive.zip](https://github.com/user-attachments/files/21949057/Archive.zip)

maybe it's the problem with the model? 

but i tested 8 other models, all of them have these 2 issues

here is the pmx files and the texture

blender version: 4.5.2

mmd tools version:4.3.10

**Comment by rintrint** [comment]
Issue 1 occurs because your model does not have SPA/SPH textures. This is not a problem.
Issue 2 happens because Unicode support needs to be enabled when exporting your model.
Thank you.

**Comment by Lcyre1** [comment]
thank you, my mistake, issue2 is not caused by spa/sph

but when i convert some model to blender, some textures didnt appear as expected

[Archive.zip](https://github.com/user-attachments/files/21950225/Archive.zip)

<img width="1296" height="766" alt="Image" src="https://github.com/user-attachments/assets/c3bf6072-a5bd-47d8-8a65-ac4226a85445" />

after convert

<img width="1287" height="750" alt="Image" src="https://github.com/user-attachments/assets/c2f6c9fe-488a-43d1-9c65-913461ab2429" />

**Comment by rintrint** [comment]
Should be fixed in daf5732. Thank you.

**Comment by Lcyre1** [comment]
seems still have this problem after apply this fix, do i need to change other files?

<img width="983" height="442" alt="Image" src="https://github.com/user-attachments/assets/808cc232-bf12-49b9-9876-308403bbccc9" />
